[package]
name = "turing-complete-manager"
version = "0.2.0"
description = "Save manager for Turing Complete"
authors = ["you"]
edition = "2021"

[lib]
name = "turing_complete_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = "2"
walkdir = "2"
chrono = "0.4"
uuid = { version = "1", features = ["v4"] }
base64 = "0.22"
